### ISSUE TITLE
Cannot resolve scoped service 'Pidget.Client.SentryClient' from root provider

### ISSUE THREAD

**Issue by offi** [mausworks/pidget#31]
Hi. I'm trying to use your project into my own. It is asp.net core 2.0 app. I have installed the last version from NuGet and tried last from releases. Also tried to create new asp.net core 2.0 project. 

Every time I had a startup error:
`Unhandled Exception: System.InvalidOperationException: Cannot resolve scoped service 'Pidget.Client.SentryClient' from root provider.`

dotnet --info and Startup.cs: https://gist.github.com/offi/2461d0f8e6e10f0c2f9d97c7372312f2

**Comment by mausworks** [comment]
Hello! I'm aware of the issue, and the fixes are actually pushed to master, I just haven't gotten to creating a release with the fixes, I've had a few busy weeks. I'll post a v1.0.1 release today. The 1.0.0 version *should* be unlisted at nuget though.

Sorry for the inconvenience.

**Comment by mausworks** [comment]
@offi I have resolved the issue and pushed the release to nuget:

https://www.nuget.org/packages/Pidget.AspNet/1.0.1

I've pulled the package, and confirmed it works using your configuration.

However, it is best to configure the middleware next to the "application code", before any other error-handlers, if they were to catch the thrown exception, it will prevent the pidget middleware from sending it to sentry. 

I'd set it up like this:

```csharp
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            // Before application code, but after exception-handlers
            app.UsePidgetMiddleware(); 
            app.UseStaticFiles();            

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

But it seems to work either way. :+1: 

Again, thanks for the issue.

**Comment by offi** [comment]
@mausworks Thanks for response. Unfortunately, it did not help me.

**Comment by mausworks** [comment]
@offi are you still having the same issues, even after updating to 1.0.1?

**Comment by offi** [comment]
@mausworks Yes, I still get the same error

**Comment by mausworks** [comment]
I unfortunately cannot reproduce the problem after updating, using the startup you provided (and setting a valid DSN/`null`), are you sure the package updated properly? Sometimes you need to `dotnet restore --force --no-cache`, to "encourage" nuget to pull the new version.

My `dotnet --info`:

```
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

If it's not to big of an issue, does the [example app](https://github.com/mausworks/pidget/tree/master/examples/Pidget.AspNetExample) compile & run on your machine? Thanks for helping.

**Comment by offi** [comment]
I have noticed that this error appears only with ASPNETCORE_ENVIRONMENT=Development, Production env works fine. It can be reproduced with your example, it works fine only in production env. 

Same error: https://github.com/aspnet/Mvc/issues/6407

**Comment by mausworks** [comment]
This is new to me. I did not know of this change.

I think having different behaviour between development and production for DI is a *really* strange design choice.

I will fix this on Wednesday. If you have the know-how and time to fix it, feel free to submit a PR :)

Thanks a lot for the help! 👍

**Comment by mausworks** [comment]
I think the easiest solution for this is to simply inject the client as either singleton transient. I'm not sure why I decided to inject it as a scoped service initially, there certainly isn't any need for it now.

**Comment by offi** [comment]
@mausworks Yes, I think it will be good solution.

**Comment by mausworks** [comment]
Ping @offi #33. Feel free to review, if it is what your heart desires. I will create release when I have solved a package-icon issue (NuGet are now really anal about not being able to edit your package after upload).

**Comment by mausworks** [comment]
Hello @offi 

A new release is up: https://www.nuget.org/packages/Pidget.AspNet/1.0.2
It should resolve the issues you're facing, but please let me know.

Thanks again for all your help. :+1:

**Comment by offi** [comment]
Yes, it helped. Now app starting without errors. Thanks for help and work on useful project.
