### ISSUE TITLE
Sentry.CreateClient raises a System.TypeInitializationException in the UWP release build

### ISSUE THREAD

**Issue by Paradoxon101** [mausworks/pidget#43]
Pidget.Client -Version 1.0.3

InnerException.InnerException.StackTrace
   bei Pidget.Client.VersionNumber.Get()
   bei Pidget.Client.SentryClient..cctor()
   bei System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext* pContext) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\ClassConstructorRunner.cs: Zeile92

**Comment by mausworks** [comment]
Hello! And thank you for your issue!

This looks very severe indeed! I will try to reproduce this, but I would appriciate a lot if you could provide more information. Thanks! :+1:

**Comment by mausworks** [comment]
OK. So I might have identified something, it's just speculation though.

My working theory is this: CoreRT will attempt to pre-compile the constructor for `SentryClient`, (hence `ClassConstructorRunner`). However: Before doing so, [the static property `SentryClient.Version`](https://github.com/mausworks/pidget/blob/6acf9d8d0d833018515b6adaef2730650f2370f2/src/Pidget.Client/SentryClient.cs#L14-L18) will attempt get set [via `VersionNumber.Get()`](https://github.com/mausworks/pidget/blob/6acf9d8d0d833018515b6adaef2730650f2370f2/src/Pidget.Client/VersionNumber.cs#L8-L10).

However; for some reason, either `Assembly.GetExecutingAssembly().Location` is not available, or `FileVersionInfo.GetVersionInfo` throws, I'm not sure entirely what's going on though. But the fix could be trivial :relieved:

**Comment by Paradoxon101** [comment]
Very interesting and thanks for the quick response!

**Comment by mausworks** [comment]
Hello again @Paradoxon101!

I have pushed [some updates](https://github.com/mausworks/pidget/commit/c47991305e5232f64e09823aa9c1d2a474ebb7c5) to the branch [`feature/refactor-tests`](https://github.com/mausworks/pidget/tree/feature/refactor-tests) which might solve your problem.

There is a caveat though; I'm currently running Arch Linux, which doesn't support running UWP (for obvious reasons), So I would be really glad if you could help me test this. If so either:

- [Download Pidget.Client.dll.zip](https://github.com/mausworks/pidget/files/1910371/Pidget.Client.dll.zip), extract it and reference it in your UWP project, then see if it runs (this compiled version has the 'fix').
- Clone the repo, or [download the source code as a zip](https://github.com/mausworks/pidget/archive/feature/refactor-tests.zip), extracting it, and then reference the project in Visual Studio directly, then again; see if it runs.

If it solves your problem, I will push the changes to NuGet ASAP! :tada: 

Thanks again :+1:

**Comment by Paradoxon101** [comment]
Unfortunately, I can not test this now, because I now use the official RavenClient. This was recently migrated to .net standard 2.0

https://github.com/getsentry/raven-csharp

**Comment by mausworks** [comment]
Very interesting! Good look in future endeavours.
