### ISSUE TITLE
Using Pidget in an ASP.NET .NET 4.6.2 application

### ISSUE THREAD

**Issue by laplace777** [mausworks/pidget#54]
I came along from reddit comments to here and want to use your package in one of my projects.

The problem is that how I will integrate it to .net 4.6.2 project in the best way to filter and having some tags sent to sentry and also in a clever way using breadcrumbs.

At the moment I wrote a console app and can write to sentry using the pidget.client but I want to use Pidget.AspNet and capture my 4.6.2 app errors.

Right now we use nlog.
I figured out also nlogs can be sent to pidget right ?

Thanks.

erkin

**Comment by mausworks** [comment]
Hi erkin, thank you for your interest in the project!

> The problem is that how I will integrate it to .net 4.6.2 project in the best way to filter and having some tags sent to sentry and also in a clever way using breadcrumbs.

Sounds good &mdash; You should be able to do that. 👍 

> At the moment I wrote a console app and can write to sentry using the pidget.client but I want to use Pidget.AspNet and capture my 4.6.2 app errors.

Let me first explain a little about the two projects.

The `Pidget.Client` is a "simple dumb client", it doesn't capture any application exceptions as a "default behavior", it is just a "transfer mechanisms" for sending errors to Sentry &mdash; but you have to provide it with the error yourself.

The `Pidget.AspNet` is an error handling middleware for [ASP.NET Core](https://github.com/aspnet/AspNetCore), which relies on the client as a transfer mechanism, but it doesn't work for "classic ASP.NET" &mdash; I should probably change the name to `Pidget.AspNetCore`.

However, if you are using ASP.NET Core, it should be pretty much "plug and play" &mdash; show me your `Startup.cs` and I might be able to help.

> I figured out also nlogs can be sent to pidget right ?

Yes, you could probably create an handler which sends NLog's to Sentry using the Pidget Client, feel free to contribute :)

**Comment by mausworks** [comment]
Closing this for now, as I'm not sure what to do. It would like to help, but I'm not sure what you're asking exactly.

I think you can still comment on this issue though. Good luck 👍
